### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by w3bb** [tsudoko/pullcord#20]
I'm trying to archive a server, and it seems to panic on the splash image of a server with error:

```
panic: assignment to entry in nil map

goroutine 29 [running]:
github.com/tsudoko/pullcord/logcache.(*Entries).WriteNew(0xc0001bd368, 0x817a60, 0xc0000b6098, 0xc00009ed00, 0xd, 0xd)
        /home/webb/go/src/github.com/tsudoko/pullcord/logcache/main.go:58 +0x172
github.com/tsudoko/pullcord/logpull.(*Puller).PullGuild(0xc0001bd350, 0xc0001c0bc0, 0x12, 0x12, 0xc0001dfd58)
        /home/webb/go/src/github.com/tsudoko/pullcord/logpull/main.go:130 +0x299
main.do(0xc0000dc3c0, 0xc00018c000)
        /home/webb/go/src/github.com/tsudoko/pullcord/cmd/pullcord/main.go:47 +0x948
github.com/tsudoko/pullcord/vendor/github.com/bwmarrin/discordgo.readyEventHandler.Handle(0x7bfbe0, 0xc0000dc3c0, 0x70eaa0, 0xc00018c000)
        /home/webb/go/src/github.com/tsudoko/pullcord/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:692 +0x57
created by github.com/tsudoko/pullcord/vendor/github.com/bwmarrin/discordgo.(*Session).handle
        /home/webb/go/src/github.com/tsudoko/pullcord/vendor/github.com/bwmarrin/discordgo/event.go:171 +0x10e
```

**Comment by w3bb** [comment]
I just deleted the splash image, and now I'm getting this error. 
```
2020/01/07 19:16:24 unsupported channel type 5
panic: unsupported channel type 5
```

**Comment by tsudoko** [comment]
Should be fixed now.

**Comment by w3bb** [comment]
I'll give it a test

**Comment by w3bb** [comment]
Seems to be working fine 👍
